# Generated by Django 6.0.4 on 2026-04-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bouquets/'),
        ),
    ]
