# Generated by Django 6.0.4 on 2026-04-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0003_alter_bouquet_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
