# Generated by Django 6.0.4 on 2026-04-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0005_event_alter_order_bouquet_bouquet_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouquet',
            old_name='event',
            new_name='events',
        ),
    ]
