# Generated by Django 6.0.4 on 2026-04-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0006_rename_event_bouquet_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='events',
            field=models.ManyToManyField(related_name='bouquets', to='flower_shop.event'),
        ),
    ]
