# Generated by Django 6.0.4 on 2026-04-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0007_alter_bouquet_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
