# Generated by Django 6.0.4 on 2026-04-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0010_bouquet_is_recommended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'ordering': ('-is_recommended',), 'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='flower_shop.bouquet'),
        ),
    ]
