# Generated by Django 6.0.4 on 2026-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0011_alter_bouquet_options_alter_order_bouquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Не оплачено')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='yookassa_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
