# Generated by Django 6.0.4 on 2026-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0013_alter_event_options_alter_flower_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время доставки по'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время доставки с'),
        ),
    ]
